### ISSUE TITLE
pytorch和OpenCV-python版本

### ISSUE THREAD

**Issue by sleepy-syr** [hpc203/10kinds-light-face-detector-align-recognition#2]
遇到报错

`Traceback (most recent call last):
  File "D:/Project/10kinds-light-face-detector-align-recognition-master/10kinds-light-face-detector-align-recognition-master/Run_all_compare_time.py", line 35, in <module>
    retinaface_dnn_detect = retinaface_dnn(align=align)
  File "D:\Project\10kinds-light-face-detector-align-recognition-master\10kinds-light-face-detector-align-recognition-master\retinaface_detect_align_module.py", line 45, in __init__
    self.net = RetinafaceDetector_dnn()
  File "D:\Project\10kinds-light-face-detector-align-recognition-master\10kinds-light-face-detector-align-recognition-master\retinaface\detector.py", line 121, in __init__
    self.model = cv2.dnn.readNetFromONNX(model_path)`

`cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\layers\eltwise_layer.cpp:116: error: (-215:Assertion failed) inputs[0] == inputs[i] in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'`

是OpenCV版本问题么

**Comment by hpc203** [comment]
这个是opencv版本的问题，建议更新到最新版的opencv4.4.0
在终端输入pip install --upgrade opencv-python

**Comment by sleepy-syr** [comment]
已解决，谢谢
